#rep_dir: "C:/repVGG"
TRAIN_DATA_DIR: "C:/repVGG/datasets/8/roi"
VAL_DATA_DIR: "C:/repVGG/datasets/8/roi-test"
net_name: res2net
ENABLE_DEPLOY_REPVGG: False
DO_TRAIN: True
ENABLE_VALIDATION: True
IMAGE_SIZE: 32
BATCH_SIZE: 300
nums_epoch: 50
date: '-20220711-8cls-res2net-finetune-b-3-3-3-3'
channel_list: [
 "16-32-48-64",       #16-32-64-64
]
num_of_ch: 4
block_num:
 - 3
 - 3
 - 3
 - 3
num_classes: 8
class_names: ['GreenLeft', 'GreenRight', 'GreenStraight','RedLeft','RedRight','YellowLeft','YellowRight','others'] 

